### ISSUE TITLE
Add-migration not workin

### ISSUE THREAD

**Issue by rajexact** [MdSazzadIslam/College-Management-System#1]
I AM TRYING TO RESOLVE THE ISSUE BUT ITS STUCK  WHILE ADD-MIGRATION
AND ERROR  THAT CANT BUILT PROJECT

**Comment by MdSazzadIslam** [comment]
Please carefully read the Readme file.

**Comment by MdSazzadIslam** [comment]
> I AM TRYING TO RESOLVE THE ISSUE BUT ITS STUCK WHILE ADD-MIGRATION
> AND ERROR THAT CANT BUILT PROJECT

Please carefully read the Readme file
